name: Create Release
on:
  workflow_dispatch:
    inputs:
      PreReleased:
        required: false
        type: choice
        description: Pre Release ?
        default: 'yes'
        options:
          - 'no'
          - 'yes'

jobs:
  Init:
    name: Release CICD
    runs-on: 'ubuntu-latest'    
    steps:
      - uses: actions/checkout@v2

      - name: Fetch all tags
        run: |
          git fetch --tags
          git fetch --prune --unshallow
      - name: Install Go
        run: |
          VERSION="1.18.5"
          ARCH="amd64"
          curl -O -L "https://go.dev/dl/go${VERSION}.linux-${ARCH}.tar.gz"
          sudo tar -C /usr/local -xzf go${VERSION}.linux-${ARCH}.tar.gz
          echo "export GOPATH=$HOME/go" >> ~/.bash_profile
          echo "export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" >> ~/.bash_profile
          source ~/.bash_profile
          go version

      - name: Run Tests
        run: |

      - name: Build with version
        id: version
        run: |
          releaseDate=`date -u +%d-%m-%Y`
          releaseTime=`date -u +%H:%M:%S`
          build=${{ github.run_number }}
          version=$(go run -ldflags "-X cloudflare/cmd.build=$build -X 'cloudflare/cmd.releaseDate=$releaseDate $releaseTime'" main.go version -s)
          echo "::notice title=Version :: ${version}"

          GOOS=linux GOARCH=amd64 go build -ldflags "-X cloudflare/cmd.build=$build -X 'cloudflare/cmd.releaseDate=$releaseDate $releaseTime'" \
                                                      -o "release/linux-amd64-$version/cloudflare" cloudflare
          cd release/linux-amd64-$version
          tar -czvf linux-amd64-$version.tar.gz cloudflare
          cd ..
          cd ..

          GOOS=darwin GOARCH=arm64 go build -ldflags "-X cloudflare/cmd.build=$build -X 'cloudflare/cmd.releaseDate=$releaseDate $releaseTime'" \
                                                      -o "release/darwin-arm64-$version/cloudflare" cloudflare
          cd release/darwin-arm64-$version
          tar -czvf darwin-arm64-$version.tar.gz cloudflare
          cd ..
          cd ..

          GOOS=windows GOARCH=amd64 go build -ldflags "-X cloudflare/cmd.build=$build -X 'cloudflare/cmd.releaseDate=$releaseDate $releaseTime'" \
                                                      -o "release/windows-amd64-$version/cloudflare" cloudflare
          cd release/windows-amd64-$version
          tar -czvf windows-amd64-$version.zip cloudflare
          cd ..
          cd ..

          previousTag=$(git tag --sort=committerdate | tail -1)
          currentTag=$version

          git tag $currentTag
          git push --tags

          IFS='' && releaseText=$(git log --pretty=format:"%h | %s"  $currentTag ^$previousTag)
          echo "### Features: " > body.txt
          echo $releaseText >> body.txt

          echo "::set-output name=tag::$currentTag"
          echo "::set-output name=releaseText::$releaseText"

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Cloudflare CLI ${{ steps.version.outputs.tag }}
          body_path: body.txt
          draft: false
          prerelease: ${{ github.event.inputs.PreReleased == 'yes' }}
      
      - name: Upload Linux Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/linux-amd64-${{ steps.version.outputs.tag }}/linux-amd64-${{ steps.version.outputs.tag }}.tar.gz
          asset_name: linux-amd64-${{ steps.version.outputs.tag }}.tar.gz
          asset_content_type: application/zip
      
      - name: Upload Darwin Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/darwin-arm64-${{ steps.version.outputs.tag }}/darwin-arm64-${{ steps.version.outputs.tag }}.tar.gz
          asset_name: darwin-arm64-${{ steps.version.outputs.tag }}.tar.gz
          asset_content_type: application/zip

      - name: Upload Windows Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/windows-amd64-${{ steps.version.outputs.tag }}/windows-amd64-${{ steps.version.outputs.tag }}.zip
          asset_name: windows-amd64-${{ steps.version.outputs.tag }}.zip
          asset_content_type: application/zip          