name: Unit Test
on:
  push:
    paths:
      - "**/pkg/**"
  workflow_dispatch:
jobs:
  Test:
    name: Run Unit Test
    runs-on: 'ubuntu-latest'    
    steps:
      - uses: actions/checkout@v2

      - name: Fetch all tags
        run: |
          git fetch --tags
          git fetch --prune --unshallow
      - name: Install Go
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          wget https://dl.google.com/go/go1.18.5.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go1.18.5.linux-amd64.tar.gz

          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          source ~/.bashrc

          go version

      - name: Run All Tests
        run: |
          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          source ~/.bashrc

          go version
          go test ./...